# Jekyll Resume Theme

# Site settings
title: Jekyll Resume
email: email@domain.com
description: Jekyll Resume is a mega simple resume theme for Jekyll.
baseurl: "/jekyll-resume"
url: "http://liuyu19.github.io"
name: LiuYu
job: front end engineer
location: Guangzhou, China
languages: HTML, CSS and Javascript
twitter_username: liuyu19
github_username:  liuyu19
codepen_username:  liuyu19
email_address: some@email.com

# Build settings
markdown: kramdown
